export const CALL_API = 'CALL_API'

export const OFF_TANGLE_USERS_REQUEST = 'OFF_TANGLE_USERS_REQUEST'
export const OFF_TANGLE_USERS_FAILURE = 'OFF_TANGLE_USERS_FAILURE'
export const OFF_TANGLE_USERS_SUCCESS = 'OFF_TANGLE_USERS_SUCCESS'

export const CHECK_TANGLE_USERS_REQUEST = 'CHECK_TANGLE_USERS_REQUEST'
export const CHECK_TANGLE_USERS_FAILURE = 'CHECK_TANGLE_USERS_FAILURE'
export const CHECK_TANGLE_USERS_SUCCESS = 'CHECK_TANGLE_USERS_SUCCESS'
