export const CALL_API = 'CALL_API';

export const OFF_TANGLE_USERS_REQUEST = 'OFF_TANGLE_USERS_REQUEST';
export const OFF_TANGLE_USERS_FAILURE = 'OFF_TANGLE_USERS_FAILURE';
export const OFF_TANGLE_USERS_SUCCESS = 'OFF_TANGLE_USERS_SUCCESS';

export const CREATE_CLAIM_REQUEST = 'CREATE_CLAIM_REQUEST';
export const CREATE_CLAIM_FAILURE = 'CREATE_CLAIM_FAILURE';
export const CREATE_CLAIM_SUCCESS = 'CREATE_CLAIM_SUCCESS';

export const UPDATE_LOCAL_ACCOUNT_REQUEST = 'UPDATE_LOCAL_ACCOUNT_REQUEST';
export const UPDATE_LOCAL_ACCOUNT_FAILURE = 'UPDATE_LOCAL_ACCOUNT_FAILURE';
export const UPDATE_LOCAL_ACCOUNT_SUCCESS = 'UPDATE_LOCAL_ACCOUNT_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';
